#!/bin/bash

if [[ $# -eq 0 ]] ; then
    echo "Usage: $(basename $BASH_SOURCE) [fileprefix ...]"
    exit 1
fi

for prefix in "$@"; do
    if [[ -e $prefix.html ]]; then
        echo "$prefix.html already exists!"
        exit 2
    fi
done

for prefix in "$@"; do
    cat >$prefix.html <<EOF
<html>

<head>
  <title>$prefix</title>

  <!-- UNCOMMENT FOR INCLUDING CUSTOM CSS
  <link href="css/site.css" rel="stylesheet"></link>
  -->
</head>

<body>

  <!-- UNCOMMENT FOR DEV VERSION OF REACT
  <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>

<script src="https://unpkg.com/react@17/umd/react.development.js" crossorigin></script>
  <script src="https://unpkg.com/react-dom@17/umd/react-dom.development.js" crossorigin></script>

  <script type="text/babel" src="your-react-file.js"></script>
  -->
</body>

</html>
EOF
done

